services:
  - type: web
    name: spotify-search-bot
    env: python
    buildCommand: apt-get update && apt-get install -y portaudio19-dev python3-dev && pip install -r requirements.txt && python setup_production.py
    startCommand: gunicorn app:app
    envVars:
      - key: SPOTIPY_CLIENT_ID
        value: 112198efe8bc4ae49492ad78031679a8
      - key: SPOTIPY_CLIENT_SECRET
        value: 9deeb3255e3d4d7187903c8b5ae2dd90
      - key: SPOTIPY_REDIRECT_URI
        value: https://spotify-search-bot.onrender.com/callback
      - key: AUDD_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: spotify-data
      mountPath: /data
      sizeGB: 1

